version: 0.0
os: linux
files:
  - source: /index.php
    destination: /var/www/dotproject/
    - source: /classes
    destination: /var/www/dotproject/
    - source: /db
    destination: /var/www/dotproject/
    - source: /files
    destination: /var/www/dotproject/
    - source: /functions
    destination: /var/www/dotproject/
    - source: /images
    destination: /var/www/dotproject/
permissions:
  - object: /var/www/dotproject/
    owner: root
    group: root
    mode: 777
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
    - location: scripts/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root


